// Fichier app/layout.tsx: définit le squelette HTML: balises <html>, thèmes daisyUI...

// ----------- IMPORTS -----------
// le type `Metadata` fourni par Next.js pour typer les métadonnées (SEO : title, description...)
import type { Metadata } from "next";

// Importer 2 polices google pour optimiser le chargement
import { Geist, Geist_Mono } from "next/font/google";
 
// Styles par défaut générés avec Tailwind
import "./globals.css";

// ----------- CONFIG FONTS -----------
// Chargement des 2 fonts google
const geistSans = Geist({
  variable: "--font-geist-sans",  
  subsets: ["latin"],             
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ----------- METADATA (SEO) -----------
// Paramétrer le titre / la descirption de l'app
export const metadata: Metadata = {
  title: "Skill Share",            
  description: "Generated by create next app",  
};

// ----------- ROOT LAYOUT -----------
// composant principal de layout
export default function RootLayout({
  // prop spéciale affiché à l'intérieur du layout
  children,
}: Readonly<{
  children: React.ReactNode; // n’importe quel élément React (composants/pages)
}>) {
  return (
    <html lang="fr" >
      {/* Définir la balise <body> de toutes tes pages. */}
      <body
        // applique les variable CSS des 2 fonts google avec la classe Tailwind `antialiased` (lissage du texte)
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/*  Ici s'afficheront toutes les pages de l'app (injectées par Next.js) */}
      </body>
    </html>
  );
}
